### ISSUE TITLE
.yaml test Filler format

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#385]
I've studied yaml format and could tell that a test format could look like this: 

```
#description of a test
---
add12:
  env:
    currentCoinbase: 2adc25665018aa1fe0e6bc666dac8fc2697ff9ba
    currentDifficulty: '0x20000'
    currentGasLimit: '1000000'
    currentNumber: '1'
    currentTimestamp: '1000'
    previousHash: 5e20a0453cecd065ea59c37ac63e079ee08998b6045136a8ce6635c7912ec0b6
  expect:
  - indexes:
      data: !!int -1
      gas: !!int -1
      value: !!int -1
    network:
    - ALL
    result:
      #explanation why we expect such a result here
      095e7baea6a6c7c4c2dfeb977efac326af552d87:
        balance: '1000000000000100000'
        code: '0x6001600101600055'
        storage:
          0x: '0x02'
      2adc25665018aa1fe0e6bc666dac8fc2697ff9ba:
        balance: '41012'
        code: 0x
        nonce: '0'
        storage: {}
      a94f5374fce5edbc8e2a8697c15331677e6ebf0b:
        balance: '999999999999858988'
        code: 0x
        nonce: '1'
        storage: {}
  pre:
    095e7baea6a6c7c4c2dfeb977efac326af552d87:
      balance: '1000000000000000000'
      code: '0x6001600101600055'
      nonce: '0'
      storage: {}
    a94f5374fce5edbc8e2a8697c15331677e6ebf0b:
      balance: '1000000000000000000'
      code: >-
         multiline solididy 
         or whatever code here
      nonce: '0'
      storage: {}
  transaction:
    data:
    #description of a data field
    - ''
    gasLimit:
    - '400000'
    gasPrice: '1'
    nonce: '0'
    secretKey: 45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8
    to: 095e7baea6a6c7c4c2dfeb977efac326af552d87
    value:
    - '100000'

```

**Comment by pirapira** [comment]
Oh, you can have proper comments!

**Comment by gumb0** [comment]
How would a multi-line code look in there?

**Comment by winsvega** [comment]
```
code: >- 
                0x6001600101600055
                003344556633a234
```

```
- code: >-
             Some July code here
             and even more code here
```

**Comment by winsvega** [comment]
updated test format. this is automatic jsonToYaml converter output;
https://www.json2yaml.com/

if the field is int it should be prefixed like 
```data: !!int -1```

all other fields are assumed to be json string fields.

**Comment by winsvega** [comment]
ok. here is one of the downsides of yml format:
although I think data could be passed as array in one line. this is the result of automatic convertion.
and you have to manually add !!int to each integer field after json2yaml convert tool

```
---
add12:
  env:
    currentCoinbase: 2adc25665018aa1fe0e6bc666dac8fc2697ff9ba
    currentDifficulty: '0x20000'
    currentGasLimit: '1000000'
    currentNumber: '1'
    currentTimestamp: '1000'
    previousHash: 5e20a0453cecd065ea59c37ac63e079ee08998b6045136a8ce6635c7912ec0b6
  expect:
  - indexes:
      data:
      - !!int 0
      gas: !!int 0
      value: !!int 0
    network:
    - ALL
    result:
      6295ee1b4f6dd65047762f924ecd367c17eabf8f: {}
  - indexes:
      data:
      - !!int 1
      - !!int 2
      - !!int 3
      - !!int 4
  ....
      - !!int 169
      - !!int 170
      - !!int 171
      gas: !!int 0
      value: !!int 0
    network:
    - ALL
    result:
      6295ee1b4f6dd65047762f924ecd367c17eabf8f:
        shouldnotexist: '1'
  pre:
    a94f5374fce5edbc8e2a8697c15331677e6ebf0b:
      balance: '1000000000000000000'
      code: 0x
      nonce: '0'
      storage: {}
  transaction:
    data:
    - '0x600160016001600160016001600160015800006000f3'
    - '0x600160016001600160016001600160010c60006000f3'
    - '0x600160016001600160016001600160010d60006000f3'
.....
    - '0x60016001600160016001600160016001f860006000f3'
    - '0x60016001600160016001600160016001f960006000f3'
    - '0x60016001600160016001600160016001fc60006000f3'
    - '0x60016001600160016001600160016001fe60006000f3'
    gasLimit:
    - '400000'
    gasPrice: '1'
    nonce: '0'
    secretKey: 45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8
    to: ''
    value:
    - '100000'
```
