### ISSUE TITLE
There should be a VM test that uses a return value of BYTE in arithmeticss

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#448]
https://github.com/ethereumjs/ethereumjs-vm/pull/293#discussion_r181039997

> This makes me think we should have test cases of the format x y DUP1 BYTE ADD

**Comment by jwasinger** [comment]
fixed by https://github.com/ethereum/tests/pull/454

**Comment by winsvega** [comment]
@qbzzt apparently there is evm byte instruction unreachable from lll. And there was some issue around it

**Comment by qbzzt** [comment]
> @qbzzt apparently there is evm byte instruction unreachable from lll. And there was some issue around it

There is a `BYTE` opcode (https://web.archive.org/web/20201109185700/https://ethervm.io/#1A), but it is reachable from LLL (https://github.com/qbzzt/tests/blob/vmtests-for-merge-20210228/src/GeneralStateTestsFiller/VMTests/vmBitwiseLogicOperation/byteFiller.yml).

Most tests just write the results of `BYTE` to storage, but the test that is now in contract 0x010A has dup. 

```
    000000000000000000000000000000000000010a:
      balance: '0x0ba1a9ce0ba1a9ce'
      #  0 PUSH5 0x1234523456
      #  6 PUSH1 0x1F   (a.k.a. 31 the least significant byte)     
      #  8 BYTE
      #  9 DUP1
      #  A ADD
      #  B PUSH1 0x01
      #  D SSTORE
      code: :raw 0x641234523456601F1A8001600155
      nonce: '0'
      storage: {}
  ```
  
  I think we can close it.
